package jsfas.db.main.persistence.repository;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import jsfas.common.constants.ApplStatusConstants;
import jsfas.common.constants.PymtStatusConstants;
import jsfas.db.CommonRepository;
import jsfas.db.main.persistence.domain.ElApplActDAO;
import jsfas.db.main.persistence.domain.ElApplHdrDAO;

public interface ElApplHdrRepository extends CommonRepository<ElApplHdrDAO, String> {
	
	@Query(value = "SELECT EL_APPL_SEQ.NEXTVAL FROM DUAL ", nativeQuery = true)
	String findNextApplNo();
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id as el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    hdr.version_no, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short, "
			+ "    prgm.dept, "
			+ "    hdr.br_post_ind, "
			+ "    hdr.pymt_post_ind "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde "
			+ "    WHERE ((hdr.appl_user_id = :remoteUser AND hdr.appl_stat_cde <> 'DRAFT') or hdr.appl_requester_id = :remoteUser) "
			+ "    AND hdr.appl_stat_cde <> '"+ ApplStatusConstants.COMPLETED +"' "
			+ "    AND hdr.obsolete = 0 "
			+ "ORDER BY appl_dttm desc " , nativeQuery = true)
	List<Map<String, Object>> findMyApplications(@Param("remoteUser") String remoteUser);
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short "
			+ "FROM "
			+ "    ( "
			+ "        SELECT "
			+ "            * "
			+ "        FROM "
			+ "            ( "
			+ "                SELECT "
			+ "                    ROW_NUMBER() "
			+ "                    OVER(PARTITION BY el_appl_aprv_status.appl_hdr_id "
			+ "                         ORDER BY "
			+ "                             el_appl_aprv_status.arpv_seq, aprv_user_id "
			+ "                    ) rn, "
			+ "                    el_appl_aprv_status.id, "
			+ "                    el_appl_aprv_status.appl_hdr_id, "
			+ "                    el_appl_aprv_status.aprv_user_id "
			+ "                FROM "
			+ "                    el_appl_aprv_status "
			+ "                WHERE "
			+ "                    el_appl_aprv_status.approved = -1 "
			+ "            ) "
			+ "        WHERE "
			+ "            rn = 1 "
			+ "            AND aprv_user_id = :remote_user "
			+ "    ) aprv "
			+ "    INNER JOIN el_appl_hdr      hdr ON hdr.id = aprv.appl_hdr_id "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde"
			+ "    WHERE hdr.obsolete = 0 AND hdr.appl_stat_cde = '"+ ApplStatusConstants.PENDING +"' "
			+ "UNION "
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde"
			+ "    WHERE hdr.obsolete = 0 AND hdr.appl_user_id = :remote_user AND hdr.appl_stat_cde = '"+ ApplStatusConstants.PENDING_APPL_ACCT +"' "
			+ "ORDER BY appl_dttm desc ", nativeQuery = true)
	List<Map<String, Object>> findPendingRemoteUserApproval(@Param("remote_user") String remoteUser);

	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_user_job_catg, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (SELECT el_type_nam FROM el_type_tab et WHERE et.id = (SELECT el_type_id FROM el_appl_el_type aet WHERE aet.appl_hdr_id = hdr.id)) el_type_nam, "
			+ "    (select listagg((crse_cde || '-' || section), ', ') WITHIN GROUP (ORDER BY appl_hdr_id) FROM el_appl_course WHERE appl_hdr_id = hdr.id) course_list, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short,"
			+ "    aprv.id aprv_id "
			+ "FROM "
			+ "    ( "
			+ "        SELECT "
			+ "            * "
			+ "        FROM "
			+ "            ( "
			+ "                SELECT "
			+ "                    ROW_NUMBER() "
			+ "                    OVER(PARTITION BY el_appl_aprv_status.appl_hdr_id "
			+ "                         ORDER BY "
			+ "                             el_appl_aprv_status.arpv_seq, aprv_user_id "
			+ "                    ) rn, "
			+ "                    el_appl_aprv_status.id, "
			+ "                    el_appl_aprv_status.appl_hdr_id, "
			+ "                    el_appl_aprv_status.aprv_user_id "
			+ "                FROM "
			+ "                    el_appl_aprv_status "
			+ "                WHERE "
			+ "                    el_appl_aprv_status.approved = -1 "
			+ "                    AND aprv_type_cde <> 'PROVOST' "
			+ "                    AND aprv_type_cde NOT LIKE 'FO%' "
			+ "            ) "
			+ "        WHERE "
			+ "            rn = 1 "
			+ "            AND aprv_user_id = :remote_user "
			+ "    ) aprv "
			+ "    INNER JOIN el_appl_hdr      hdr ON hdr.id = aprv.appl_hdr_id "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde"
			+ "    WHERE hdr.obsolete = 0 AND (hdr.appl_stat_cde = '"+ ApplStatusConstants.PENDING +"' OR hdr.appl_stat_cde = '"+ ApplStatusConstants.PENDING_PYMT_APPR +"') "
			+ "UNION "
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_user_job_catg, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (SELECT el_type_nam FROM el_type_tab et WHERE et.id = (SELECT el_type_id FROM el_appl_el_type aet WHERE aet.appl_hdr_id = hdr.id)) el_type_nam, "
			+ "    (select listagg((crse_cde || '-' || section), ', ') WITHIN GROUP (ORDER BY appl_hdr_id) FROM el_appl_course WHERE appl_hdr_id = hdr.id) course_list, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short, "
			+ "    ' ' aprv_id "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde"
			+ "    WHERE hdr.obsolete = 0 AND hdr.appl_user_id = :remote_user AND hdr.appl_stat_cde = '"+ ApplStatusConstants.PENDING_APPL_ACCT +"' "
			+ "ORDER BY appl_dttm desc ", nativeQuery = true)
	List<Map<String, Object>> findPendingRemoteUserBatchApproval(@Param("remote_user") String remoteUser);
	
	@Query(value = "SELECT "
			+ "    id, "
			+ "    appl_nbr, "
			+ "    appl_user_id, "
			+ "    appl_user_name, "
			+ "    appl_requester_id, "
			+ "    appl_requester_name, "
			+ "    appl_dttm, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_end_term) appl_end_term_desc, "
			+ "    ah.appl_stat_cde as appl_stat_cde, "
			+ "    eas.appl_stat_descr as appl_stat_descr, "
			+ "    appl_start_dt, "
			+ "    appl_end_dt, "
			+ "    SCH_CDE, "
			+ "    DEPT, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE) as dept_descr_short, "
			+ "    PRGM_CDE, "
			+ "    pymt_amt, "
			+ "    pmt_currency, "
			+ "    mod_ctrl_txt, "
			+ "    accepted, "
			+ "    ah.br_post_ind as br_post_ind, "
			+ "    ah.pymt_post_ind as pymt_post_ind "
			+ "FROM el_appl_hdr ah "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, SUM(pymt_amt) as pymt_amt, pmt_currency "
			+ "FROM el_appl_el_type "
			+ "GROUP BY appl_hdr_id, pmt_currency "
			+ ") aet "
			+ "ON ah.id = aet.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, sch_cde, dept, prgm_cde "
			+ "FROM el_appl_prgm "
			+ ") ap "
			+ "ON ah.id = ap.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, min(accepted) as accepted "
			+ "FROM el_appl_loa "
			+ "GROUP BY appl_hdr_id "
			+ ") al "
			+ "ON ah.id = al.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_stat_descr, appl_stat_cde "
			+ "FROM el_appl_stat_tab "
			+ ") eas "
			+ "ON eas.appl_stat_cde = ah.appl_stat_cde "
			+ "WHERE (ah.appl_requester_id = :user_id "
			+ "OR (ah.appl_user_id = :user_id AND ah.appl_stat_cde NOT IN ('ISSUE_OFFER', 'OFFER_REJECTED', 'PENDING_RECTIFY')) "
			+ ") "
			+ "AND ah.appl_stat_cde <> 'DRAFT' "
			+ "AND ah.appl_stat_cde <> 'PENDING_APPL_ACCT' "
			+ "AND ah.appl_stat_cde <> 'PENDING' "
			+ "AND ah.appl_stat_cde <> 'REJECTED' "
			+ "AND ah.appl_stat_cde <> 'REMOVED' "
			+ "AND ah.appl_stat_cde <> 'APPROVED' "
			+ "ORDER BY appl_dttm DESC", nativeQuery = true)
	List<Map<String, Object>> findApprovedByUserId(@Param("user_id") String userid);
	
	@Query(value="SELECT id, appl_user_id, appl_user_name, appl_requester_id, appl_requester_name, el_type_descr, appl_start_dt, appl_end_dt, pymt_amt, pymt_type_cde, sch_cde, mod_ctrl_txt, accepted "
			+ ", ah.appl_stat_cde "
			+ "FROM el_appl_hdr ah "
			+ "LEFT JOIN "
			+ "( "
			+ "    SELECT appl_hdr_id, el_type_descr, pmt_currency, SUM(pymt_amt) as pymt_amt, pymt_type_cde "
			+ "    FROM el_appl_el_type aet "
			+ "    LEFT JOIN "
			+ "    ( "
			+ "        SELECT appl_el_type_id, pymt_type_cde "
			+ "        FROM el_appl_pymt_method "
			+ "    ) apm "
			+ "    ON aet.id = apm.appl_el_type_id "
			+ "    GROUP BY appl_hdr_id, el_type_descr, pmt_currency, pymt_type_cde "
			+ ") aet "
			+ "ON ah.id = aet.appl_hdr_id "
			+ " "
			+ "LEFT JOIN "
			+ "( "
			+ "    SELECT appl_hdr_id, sch_cde "
			+ "    FROM el_appl_prgm "
			+ ") ap "
			+ "ON ah.id = ap.appl_hdr_id "
			+ ""
			+ "LEFT JOIN "
			+ "("
			+ "    SELECT appl_hdr_id, min(accepted) as accepted "
			+ "    FROM el_appl_loa "
			+ "    GROUP BY appl_hdr_id "
			+ ") al "
			+ "ON ah.id = al.appl_hdr_id "
			+ ""
			+ "WHERE id = :id "
			+ "ORDER BY  el_type_descr ", nativeQuery = true)
	List<Map<String, Object>> findDetailsById(@Param("id") String id);
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id as el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    hdr.version_no, " // 20231228 #393 add version number to show if amendment
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short, "
			+ "    hdr.br_post_ind,"
			+ "    hdr.pymt_post_ind "
			+ "    , (SELECT sum(pymt_amt) FROM el_appl_el_type appl_el WHERE appl_el.appl_hdr_id = hdr.id) pymt_amt_sum "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde "
			+ "    WHERE (hdr.appl_user_id = :remoteUser or hdr.appl_requester_id = :remoteUser) "
			+ "    AND hdr.obsolete = 0 "
			+ "    AND hdr.appl_stat_cde IN :statusList "
			+ "ORDER BY appl_dttm desc " , nativeQuery = true)
	List<Map<String, Object>> findPymts(@Param("remoteUser") String remoteUser, @Param("statusList") List<String> statusList);
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    hdr.version_no, " // 20231228 #393 add version number to show if amendment
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    hdr.br_post_ind,"
			+ "    hdr.pymt_post_ind, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short "
			+ "    , (SELECT sum(pymt_amt) FROM el_appl_el_type appl_el WHERE appl_el.appl_hdr_id = hdr.id) pymt_amt_sum "
			+ "	   , (SELECT MAX(action_dttm) FROM EL_APPL_ACT "
			+ "		 WHERE appl_hdr_id = hdr.id AND hdr.appl_stat_cde = 'PENDING_FOPNB' AND action_dttm >= (SELECT max(action_dttm) FROM EL_APPL_ACT WHERE appl_hdr_id = hdr.id AND ACTION = '" + ElApplActDAO.SUBMIT_PYMT + "')) latest_action_dttm "
			+ "FROM "
			+ "    ( "
			+ "        SELECT "
			+ "            * "
			+ "        FROM "
			+ "            ( "
			+ "                SELECT "
			+ "                    ROW_NUMBER() "
			+ "                    OVER(PARTITION BY el_appl_aprv_status.appl_hdr_id "
			+ "                         ORDER BY "
			+ "                             el_appl_aprv_status.arpv_seq, aprv_user_id "
			+ "                    ) rn, "
			+ "                    dense_rank()  "
			+ "			           OVER(PARTITION BY el_appl_aprv_status.appl_hdr_id  "
			+ "			           		ORDER BY  "
			+ "			                	el_appl_aprv_status.arpv_seq "
			+ "			           ) seq_rn, "
			+ "                    el_appl_aprv_status.id, "
			+ "                    el_appl_aprv_status.appl_hdr_id, "
			+ "                    el_appl_aprv_status.aprv_user_id, "
			+ "                    el_appl_aprv_status.aprv_type_cde "
			+ "                FROM "
			+ "                    el_appl_aprv_status "
			+ "                WHERE "
			+ "                    el_appl_aprv_status.approved = -1 "
			+ "            ) "
			+ "        WHERE "
			+ "            (rn = 1 AND aprv_user_id = :remote_user) "
			+ "			   OR (seq_rn = 1 AND aprv_type_cde in ('FO_SR', 'FO_SFM' ,'FO_PNB', 'FO_RECTIFY') AND aprv_user_id = :remote_user) "
			+ "    ) aprv "
			+ "    INNER JOIN el_appl_hdr      hdr ON hdr.id = aprv.appl_hdr_id "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde "
			+ "WHERE hdr.obsolete = 0 "
			+ "    AND hdr.appl_stat_cde IN :statusList "
			+ "ORDER BY appl_dttm desc ", nativeQuery = true)
	List<Map<String, Object>> findPymtPendingRemoteUserApproval(@Param("remote_user") String remoteUser, @Param("statusList") List<String> statusList);
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
//			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    hdr.version_no, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short "
			+ "    , (SELECT sum(pymt_amt) FROM el_appl_el_type appl_el WHERE appl_el.appl_hdr_id = hdr.id) pymt_amt_sum "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde "
			+ "WHERE "
			+ "    (hdr.appl_user_id = :remoteUser or hdr.appl_requester_id = :remoteUser "
			+ "	    OR (hdr.id IN ("
								+ "SELECT a.appl_hdr_id FROM el_appl_act a "
								+ "INNER JOIN                "
								+ "( SELECT "
								+ "                    appl_hdr_id, "
								+ "                    MAX(action_dttm) maxSubmitDt "
								+ "                FROM "
								+ "                    el_appl_act "
								+ "                WHERE "
								+ "                    action = '"+ ElApplActDAO.SUBMIT_APPL + "' "
								+ "                GROUP BY  "
								+ "                    appl_hdr_id "
								+ ") b ON a.appl_hdr_id = b.appl_hdr_id AND a.action_dttm >= maxSubmitDt "
								+ "WHERE "
								+ "a.action_by = :remoteUser "
								+ "AND a.action = 'Approve'"
						+ ")"
			+ "		  )"
			+ "    )  "
			+ "    AND (UPPER(hdr.appl_user_id) LIKE '%' || UPPER(:appl_name) || '%' OR UPPER(hdr.appl_user_name) LIKE '%' ||  UPPER(:appl_name) || '%') "
			+ "    AND (:appl_dttm = TO_DATE('17/11/1858', 'DD/MM/YYYY') OR trunc(hdr.appl_dttm) = trunc(:appl_dttm) )  "
			+ "    AND hdr.appl_nbr LIKE :appl_nbr  "
			+ "    AND hdr.appl_stat_cde IN :status_list  "
			+ "    AND (:appl_term = '%%' OR (TRIM(hdr.appl_end_term) is not NULL AND :appl_term BETWEEN hdr.appl_start_term AND hdr.appl_end_term) OR (:appl_term = hdr.appl_start_term)) "
			+ "    AND nvl(prgm.sch_cde, ' ') LIKE :sch_cde  "
			+ "    AND nvl(prgm.prgm_cde, ' ') LIKE :prgm_cde  "
			+ "    AND NOT ((trunc(hdr.appl_end_dt) < trunc(:appl_start_dt) OR trunc(hdr.appl_start_dt) > trunc(:appl_end_dt))) "
			+ "    ORDER BY  appl_dttm desc ", nativeQuery = true)
	List<Map<String, Object>> searchAll(@Param("remoteUser") String remoteUser, @Param("appl_name") String applName
			, @Param("appl_dttm") Timestamp applDttm, @Param("appl_nbr") String applNbr, @Param("status_list") List<String> statusList
			, @Param("appl_term") String applTerm , @Param("sch_cde") String schCde , @Param("prgm_cde") String prgmCde
			, @Param("appl_start_dt") Timestamp applStartDt, @Param("appl_end_dt") Timestamp applEndDt);
	
	@Query(value=""
			+ "SELECT ah.id as appl_hdr_id, "
			+ "			    ah.payroll_descr, "
			+ "			    aps.id as schedule_id, "
			+ "			    ah.appl_user_emplid as appl_user_emplid, "
			+ "			    aet.id as appl_el_type_id, "
			+ "			    aps.sal_elemnt, "
			+ "			    to_char(aps.pymt_start_dt, 'DD/MM/YYYY') as pymt_start_dt, "
			+ "			    to_char(aps.pymt_end_dt, 'DD/MM/YYYY') as pymt_end_dt, "
			+ "				to_char(aps.pymt_rev_start_dt, 'DD/MM/YYYY') as pymt_rev_start_dt, "
			+ "				to_char(aps.pymt_rev_end_dt, 'DD/MM/YYYY') as pymt_rev_end_dt, "
			+ "				aps.empl_nbr as emp_rec_nbr, "
			+ "			    apm.pymt_type_cde, "
			+ "			    aet.pmt_currency, "
			+ "			    aps.pymt_line_amt, "
			+ "			    to_char(ah.appl_start_dt, 'DD/MM/YYYY') as appl_start_dt, "
			+ "			    to_char(ah.appl_end_dt, 'DD/MM/YYYY') as appl_end_dt, "
			+ "			    aet.el_type_descr, "
			+ "			    aps.acct_cde, "
			+ "			    aps.analysis_cde, "
			+ "			    aps.fund_cde, "
			+ "			    aps.dept_id, "
			+ "			    aps.proj_id, "
			+ "			    aps.class_cde as class, "
			+ "			    aps.br_no as br_no, "
			+ "				aps.br_line_no, "
			+ "				aps.br_dist_line_no, "
			+ "				aps.br_post_ind, "
			+ "			    ROUND(to_number(ah.appl_user_emplid) / (ABS(0 + 0 + 0 + 0 + aps.pymt_line_amt) +1), 3) as hash_value,"
			+ "             (SELECT CASE WHEN EXISTS ( SELECT * FROM el_appl_pymt_method apm WHERE apm.appl_hdr_id = aps.appl_hdr_id "
			+ "                                        AND apm.pymt_category = 'MPF' "
			+ "                                        AND apm.pymt_amt > 0 "
			+ "             					     ) THEN 'Y' ELSE 'N' END  FROM DUAL) hv_mpf, "
			+ "             (NVL((SELECT SUM(mpf_aps.pymt_line_amt) FROM el_appl_pymt_schedule mpf_aps  "
			+ "              INNER JOIN el_appl_pymt_method mpf_apm ON mpf_aps.appl_pymt_method_id = mpf_apm.id AND mpf_apm.pymt_category = 'MPF' "
			+ "              WHERE aps.appl_hdr_id = mpf_aps.appl_hdr_id AND trunc(aps.pymt_start_dt, 'mm') = trunc(mpf_aps.pymt_start_dt, 'mm') GROUP BY trunc(mpf_aps.pymt_start_dt, 'mm')), 0)) mpf_amt"
			+ "			FROM el_appl_pymt_schedule aps "
			+ "			LEFT JOIN "
			+ "			    el_appl_pymt_method apm "
			+ "			    ON aps.appl_pymt_method_id = apm.id "
			+ "			LEFT JOIN "
			+ "			    el_appl_el_type aet "
			+ "			    ON aet.id = apm.appl_el_type_id  "
			+ "			LEFT JOIN "
			+ "			    el_appl_hdr ah "
			+ "			    ON ah.id = aps.appl_hdr_id "
			+ "			WHERE pymt_type_cde <> 'RECURR' "
			+ "			    AND ah.id = :id "
			+ "			    AND apm.pymt_category = 'SALARY' "
			+ "				AND aps.pymt_submit_dttm <> to_date('17/11/1858', 'DD/MM/YYYY') "
			+ "				AND aps.pymt_status_cde = '" + PymtStatusConstants.SUBMIT +  "' " , nativeQuery = true)
	List<Map<String, Object>> findPaymentNotRecurrById(@Param("id") String id);
	
	@Query(value=""
			+ "SELECT ah.id as appl_hdr_id, "
			+ "			    aps.id as schedule_id, "
			+ "			    ah.appl_user_emplid as appl_user_emplid, "
			+ "			    aet.id as appl_el_type_id, "
			+ "			    aps.sal_elemnt, "
			+ "			    to_char(aps.pymt_start_dt, 'DD/MM/YYYY') as pymt_start_dt, "
			+ "			    to_char(aps.pymt_end_dt, 'DD/MM/YYYY') as pymt_end_dt, "
			+ "				to_char(aps.pymt_rev_start_dt, 'DD/MM/YYYY') as pymt_rev_start_dt, "
			+ "				to_char(aps.pymt_rev_end_dt, 'DD/MM/YYYY') as pymt_rev_end_dt, "
			+ "				aps.empl_nbr as emp_rec_nbr, "
			+ "			    apm.pymt_type_cde, "
			+ "			    aet.pmt_currency, "
			+ "			    aps.pymt_line_amt, "
			+ "			    to_char(ah.appl_start_dt, 'DD/MM/YYYY') as appl_start_dt, "
			+ "			    to_char(ah.appl_end_dt, 'DD/MM/YYYY') as appl_end_dt, "
			+ "			    aet.el_type_descr, "
			+ "			    aps.acct_cde, "
			+ "			    aps.analysis_cde, "
			+ "			    aps.fund_cde, "
			+ "			    aps.dept_id, "
			+ "			    aps.proj_id, "
			+ "			    aps.class_cde as class, "
			+ "			    aps.br_no as br_no, "
			+ "				aps.br_line_no, "
			+ "				aps.br_dist_line_no, "
			+ "				aps.br_post_ind, "
			+ "			    ROUND(to_number(ah.appl_user_emplid) / (ABS(0 + 0 + 0 + 0 + aps.pymt_line_amt) +1), 3) as hash_value "
			+ "			FROM el_appl_pymt_schedule aps "
			+ "			LEFT JOIN "
			+ "			    el_appl_pymt_method apm "
			+ "			    ON aps.appl_pymt_method_id = apm.id "
			+ "			LEFT JOIN "
			+ "			    el_appl_el_type aet "
			+ "			    ON aet.id = apm.appl_el_type_id  "
			+ "			LEFT JOIN "
			+ "			    el_appl_hdr ah "
			+ "			    ON ah.id = aps.appl_hdr_id "
			+ "			WHERE pymt_type_cde = 'RECURR' "
			+ "			    AND ah.id = :id "
			+ "			    AND apm.pymt_category = 'SALARY' "
			+ "				AND aps.pymt_submit_dttm <> to_date('17/11/1858', 'DD/MM/YYYY') "
			+ "				AND aps.pymt_status_cde = '" + PymtStatusConstants.SUBMIT +  "' " , nativeQuery = true)
	List<Map<String, Object>> findPaymentIsRecurrById(@Param("id") String id);

	@Query(value="SELECT * from EL_APPL_HDR "
			+ "Where APPL_STAT_CDE = 'APPROVED' "
			+ "AND (BR_POST_IND = 'Y' OR BR_POST_IND = 'E') "
			+ "AND version_no = 1 "
			+ "AND OBSOLETE = 0 ", nativeQuery = true)
	List<ElApplHdrDAO> findAllBrPosted();

	@Query(value=""
			+ "SELECT id "
			+ "FROM el_appl_hdr "
			+ "WHERE appl_stat_cde = '" + ApplStatusConstants.PYMT_SUBM + "' "
			+ "    AND PYMT_POST_IND = 'I' "
			+ "    AND BR_POST_IND = 'Y' " , nativeQuery = true)
	List<String> findPendingPaymentId();
	
	@Query(value=""
			+ "SELECT hdr.* FROM EL_APPL_HDR hdr "
			+ "JOIN EL_APPL_COURSE crse ON hdr.id = crse.appl_hdr_id "
			+ "WHERE APPL_USER_ID = :user_id "
			+ "AND ( "
			+ "    APPL_STAT_CDE <> 'DRAFT' "
			+ "    AND APPL_STAT_CDE <> 'REMOVED' "
			+ "    AND APPL_STAT_CDE <> 'RETURNED' "
			+ "    AND APPL_STAT_CDE <> 'REJECTED' "
			+ "    AND APPL_STAT_CDE <> 'PENDING_APPL_ACCT' "
			+ "    AND APPL_STAT_CDE <> 'PENDING' "
			+ ") "
			+ "AND (select acad_yr from el_acad_term_v where strm = crse.crse_term) IN "
			+ "		(select distinct acad_yr from el_acad_term_v where (TRIM(:end_term) IS NOT NULL AND strm BETWEEN :start_term AND :end_term) OR strm = :start_term ) "
			+ "UNION ALL "
			+ "SELECT hdr.* FROM EL_APPL_HDR hdr "
			+ "LEFT JOIN EL_APPL_COURSE crse ON hdr.id = crse.appl_hdr_id "
			+ "WHERE crse.id is null "
			+ "AND APPL_USER_ID = :user_id "
			+ "AND ( "
			+ "    APPL_STAT_CDE <> 'DRAFT' "
			+ "    AND APPL_STAT_CDE <> 'REMOVED' "
			+ "    AND APPL_STAT_CDE <> 'RETURNED' "
			+ "    AND APPL_STAT_CDE <> 'REJECTED' "
			+ "    AND APPL_STAT_CDE <> 'PENDING_APPL_ACCT' "
			+ "    AND APPL_STAT_CDE <> 'PENDING' "
			+ ") "
			+ "AND EXISTS ("
			+ "		(select distinct acad_yr from el_acad_term_v where (TRIM(hdr.appl_end_term) is not NULL AND strm BETWEEN hdr.appl_start_term AND hdr.appl_end_term) OR strm = hdr.appl_start_term ) "
			+ "		INTERSECT "
			+ "		(select distinct acad_yr from el_acad_term_v where (TRIM(:end_term) IS NOT NULL AND strm BETWEEN :start_term AND :end_term) OR strm = :start_term ) "
			+ ") "
			+ "AND hdr.id in ( "
			+ "    select appl_hdr_id from el_appl_el_type "
			+ "    where el_type_id = (select id from el_type_tab where upper(el_type_nam) = upper('Project Supervision'))"
			+ ")"
			+ "" , nativeQuery = true)
	List<ElApplHdrDAO> findApprovedApplWithCrseByUserIdAndSem(@Param("user_id") String userId, @Param("start_term") String start_term, @Param("end_term") String end_term);
	
	
	@Query(value=""
			+ "SELECT hdr.* FROM EL_APPL_HDR hdr "
			+ "WHERE APPL_USER_ID = :user_id "
			+ "AND ( hdr.appl_start_term <= :end_term and hdr.appl_end_term >= :start_term ) "
			+ "AND hdr.id in ( "
			+ "    select appl_hdr_id from el_appl_el_type "
			+ "    where el_type_id = (select id from el_type_tab where upper(el_type_nam) = upper('Director Fees'))"
			+ ")"
			+ "" , nativeQuery = true)
	List<ElApplHdrDAO> findApprovedApplWithDirectoFeesByUserIdAndSem(@Param("user_id") String userId, @Param("start_term") String start_term, @Param("end_term") String end_term);

	@Query(value = "SELECT "
			+ "    id, "
			+ "    appl_nbr, "
			+ "    appl_user_id, "
			+ "    appl_user_name, "
			+ "    appl_requester_id, "
			+ "    appl_requester_name, "
			+ "    appl_dttm, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_end_term) appl_end_term_desc, "
			+ "    ah.appl_stat_cde as appl_stat_cde, "
			+ "    eas.appl_stat_descr as appl_stat_descr, "
			+ "    appl_start_dt, "
			+ "    appl_end_dt, "
			+ "    SCH_CDE, "
			+ "    DEPT, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE) as dept_descr_short, "
			+ "    PRGM_CDE, "
			+ "    pymt_amt, "
			+ "    pmt_currency, "
			+ "    mod_ctrl_txt, "
			+ "    accepted, "
			+ "    ah.br_no, "
			+ "    ah.br_post_ind, "
			+ "    ah.pymt_post_ind "
			+ "FROM el_appl_hdr ah "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, SUM(pymt_amt) as pymt_amt, pmt_currency "
			+ "FROM el_appl_el_type "
			+ "GROUP BY appl_hdr_id, pmt_currency "
			+ ") aet "
			+ "ON ah.id = aet.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, sch_cde, dept, prgm_cde "
			+ "FROM el_appl_prgm "
			+ ") ap "
			+ "ON ah.id = ap.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, min(accepted) as accepted "
			+ "FROM el_appl_loa "
			+ "GROUP BY appl_hdr_id "
			+ ") al "
			+ "ON ah.id = al.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_stat_descr, appl_stat_cde "
			+ "FROM el_appl_stat_tab "
			+ ") eas "
			+ "ON eas.appl_stat_cde = ah.appl_stat_cde "
			+ "WHERE ah.appl_stat_cde NOT IN ('ISSUE_OFFER', 'OFFER_REJECTED', 'DRAFT', 'PENDING_APPL_ACCT', 'PENDING', 'REJECTED', 'REMOVED', 'APPROVED' ) "
			+ "    AND (ah.appl_stat_cde = :status OR (:status = '%%' AND ah.appl_stat_cde LIKE '%%'))  "
			+ "    AND ah.appl_stat_cde <> 'DRAFT' "
			+ "    AND ah.appl_stat_cde <> 'PENDING_APPL_ACCT' "
			+ "    AND ah.appl_stat_cde <> 'PENDING' "
			+ "    AND ah.appl_stat_cde <> 'REJECTED' "
			+ "    AND ah.appl_stat_cde <> 'REMOVED' "
			+ "    AND ah.appl_stat_cde <> 'APPROVED' "
			+ "    AND(UPPER(ah.appl_user_id) LIKE '%' || UPPER(:appl_name) || '%' OR UPPER(ah.appl_user_name) LIKE '%' ||  UPPER(:appl_name) || '%') "
			+ "    AND (UPPER(ah.appl_requester_id) LIKE '%' || UPPER(:requester_name) || '%' OR UPPER(ah.appl_requester_name) LIKE '%' ||  UPPER(:requester_name) || '%') "
			+ "    AND ah.appl_nbr LIKE '%' || :appl_nbr || '%'  "
			+ "    AND nvl((select UPPER(acad_org_descr_short) from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE), ' ') LIKE '%' || UPPER(:dept) || '%'  "
			+ "    AND UPPER(ah.br_no) LIKE '%' || UPPER(:brNo) || '%' "
			+ "ORDER BY appl_dttm DESC", nativeQuery = true)
	List<Map<String, Object>> searchLoAEnquiry(@Param("appl_name") String appl_name, 
			@Param("requester_name") String requester_name, @Param("appl_nbr") String appl_nbr, @Param("status") String status, @Param("dept") String dept, @Param("brNo") String brNo);
	
	@Query(value = "SELECT "
			+ "id, "
			+ "appl_nbr, "
			+ "appl_user_id, "
			+ "appl_user_name, "
			+ "appl_requester_id, "
			+ "appl_requester_name, "
			+ "appl_dttm, "
			+ "br_no, "
			+ "(SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_start_term) appl_start_term_desc, "
			+ "(SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = ah.appl_end_term) appl_end_term_desc, "
			+ "ah.appl_stat_cde as appl_stat_cde, "
			+ "eas.appl_stat_descr as appl_stat_descr, "
			+ "appl_start_dt, "
			+ "appl_end_dt, "
			+ "SCH_CDE, "
			+ "DEPT, "
			+ "(select acad_org_descr_short from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE) as dept_descr_short, "
			+ "PRGM_CDE, "
			+ "pymt_amt, "
			+ "pmt_currency, "
			+ "mod_ctrl_txt, "
			+ "accepted, "
			+ "ah.br_post_ind, "
			+ "ah.pymt_post_ind, "
			+ "eam.pymt_type_cde, "
			+ "eam.pymt_start_dt, "
			+ "eam.pymt_end_dt "
			+ "FROM el_appl_hdr ah "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, SUM(pymt_amt) as pymt_amt, pmt_currency "
			+ "FROM el_appl_el_type "
			+ "GROUP BY appl_hdr_id, pmt_currency "
			+ ") aet "
			+ "ON ah.id = aet.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, sch_cde, dept, prgm_cde "
			+ "FROM el_appl_prgm "
			+ ") ap "
			+ "ON ah.id = ap.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id, min(accepted) as accepted "
			+ "FROM el_appl_loa "
			+ "GROUP BY appl_hdr_id "
			+ ") al "
			+ "ON ah.id = al.appl_hdr_id "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_stat_descr, appl_stat_cde "
			+ "FROM el_appl_stat_tab "
			+ ") eas "
			+ "ON eas.appl_stat_cde = ah.appl_stat_cde "
			+ "LEFT JOIN "
			+ "("
			+ "SELECT appl_hdr_id,pymt_type_cde, pymt_start_dt, pymt_end_dt "
			+ "FROM el_appl_pymt_method "
			+ "WHERE pymt_category = 'SALARY' "
			+ ") eam "
			+ "ON eam.appl_hdr_id = ah.id "
			+ "WHERE ah.appl_stat_cde NOT IN ('ISSUE_OFFER', 'OFFER_REJECTED', 'DRAFT', 'PENDING_APPL_ACCT', 'PENDING', 'REJECTED', 'REMOVED', 'APPROVED' ) "
			+ "AND (ah.appl_stat_cde = :status OR (:status = '%%' AND ah.appl_stat_cde LIKE '%%')) "
			+ "AND (ah.appl_stat_cde='PENDING_FOPNB' OR ah.appl_stat_cde='PYMT_SUBM') "
			+ "AND(UPPER(ah.appl_user_id) LIKE '%' || UPPER(:appl_name) || '%' OR UPPER(ah.appl_user_name) LIKE '%' ||  UPPER(:appl_name) || '%') "
			+ "AND (UPPER(ah.appl_requester_id) LIKE '%' || UPPER(:requester_name) || '%' OR UPPER(ah.appl_requester_name) LIKE '%' ||  UPPER(:requester_name) || '%') "
			+ "AND ah.appl_nbr LIKE '%' || :appl_nbr || '%' "
			+ "AND nvl((select acad_org_descr_short from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE), ' ') LIKE '%' || :dept || '%' "
			+ "ORDER BY appl_dttm DESC ", nativeQuery = true)
	List<Map<String, Object>> searchPaymentStatusReport(@Param("appl_name") String appl_name, 
			@Param("requester_name") String requester_name, @Param("appl_nbr") String appl_nbr, @Param("status") String status, @Param("dept") String dept);
	
	@Query(value = ""
			+ "SELECT "
			+ "    hdr.id AS el_appl_hdr_id, "
			+ "    hdr.appl_nbr, "
			+ "    hdr.appl_user_id, "
			+ "    hdr.appl_user_name, "
			+ "    hdr.appl_requester_id, "
			+ "    hdr.appl_requester_name, "
			+ "    hdr.appl_requester_emplid, "
			+ "    hdr.appl_requester_deptid, "
			+ "    hdr.category_cde, "
			+ "    hdr.appl_dttm, "
			+ "    hdr.appl_stat_cde, "
			+ "    stat.appl_stat_descr, "
			+ "    hdr.ow2_attached_ind, "
			+ "    hdr.pymt_aprv_required, "
			+ "    hdr.mod_ctrl_txt, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_start_term) appl_start_term_desc, "
			+ "    (SELECT yr_term_desc FROM el_acad_term_v term WHERE term.strm = hdr.appl_end_term) appl_end_term_desc, "
			+ "    hdr.appl_start_dt, "
			+ "    hdr.appl_end_dt, "
			+ "    hdr.version_no, "
			+ "    prgm.prgm_cde, "
			+ "    prgm.sch_cde, "
			+ "    prgm.dept, "
			+ "    hdr.br_no, "
			+ "    (select acad_org_descr_short from el_acad_plan_v where acad_plan = prgm.prgm_cde and acad_org = prgm.dept and acad_group = prgm.sch_cde) as dept_descr_short "
			+ "    , (SELECT sum(pymt_amt) FROM el_appl_el_type appl_el WHERE appl_el.appl_hdr_id = hdr.id) pymt_amt_sum, "
			+ "    hdr.br_post_ind, "
			+ "    hdr.pymt_post_ind "
			+ "FROM "
			+ "    el_appl_hdr      hdr "
			+ "    LEFT JOIN el_appl_prgm     prgm ON hdr.id = prgm.appl_hdr_id "
			+ "    LEFT JOIN el_appl_stat_tab stat ON hdr.appl_stat_cde = stat.appl_stat_cde "
			+ "WHERE "
//			+ "    (hdr.appl_user_id = :remoteUser or hdr.appl_requester_id = :remoteUser)  "
			+ "    (UPPER(hdr.appl_user_id) LIKE '%' || UPPER(:appl_name) || '%' OR UPPER(hdr.appl_user_name) LIKE '%' ||  UPPER(:appl_name) || '%') "
			+ "    AND (UPPER(hdr.appl_requester_id) LIKE '%' || UPPER(:requester_name) || '%' OR UPPER(hdr.appl_requester_name) LIKE '%' ||  UPPER(:requester_name) || '%') "
//			+ "    AND (:appl_dttm = TO_DATE('17/11/1858', 'DD/MM/YYYY') OR trunc(hdr.appl_dttm) = trunc(:appl_dttm) )  "
			+ "    AND hdr.appl_nbr LIKE '%' || :appl_nbr || '%'  "
			+ "    AND (hdr.appl_stat_cde = :status OR (:status = '%%' AND hdr.appl_stat_cde LIKE '%%'))  "
//			+ "    AND (:appl_term = '%%' OR (:appl_term BETWEEN hdr.appl_start_term AND hdr.appl_end_term)) "
//			+ "    AND nvl(prgm.sch_cde, ' ') LIKE :sch_cde  "
//			+ "    AND nvl(prgm.prgm_cde, ' ') LIKE :prgm_cde  "
			+ "    AND nvl((select UPPER(acad_org_descr_short) from el_acad_plan_v where acad_plan = PRGM_CDE and acad_org = DEPT and acad_group = SCH_CDE), ' ') LIKE '%' || UPPER(:dept) || '%'  "
//			+ "    AND NOT ((trunc(hdr.appl_end_dt) < trunc(:appl_start_dt) OR trunc(hdr.appl_start_dt) > trunc(:appl_end_dt))) "
			+ "    AND hdr.appl_stat_cde NOT IN :status_list  "
			+ "    AND UPPER(hdr.br_no) LIKE '%' || UPPER(:brNo) || '%' "
			+ "    ORDER BY  appl_dttm desc ", nativeQuery = true)
	List<Map<String, Object>> searchApplicationEnquiry(@Param("status_list") List<String> statusList, @Param("appl_name") String appl_name, 
			@Param("requester_name") String requester_name, @Param("appl_nbr") String appl_nbr, @Param("status") String status, @Param("dept") String dept, @Param("brNo") String brNo);
	
	@Query(value=""
			+ "SELECT hdr.* FROM EL_APPL_HDR hdr "
			+ "WHERE APPL_USER_ID = :user_id "
			+ "AND ( "
			+ "    APPL_STAT_CDE <> 'DRAFT' "
			+ "    AND APPL_STAT_CDE <> 'REMOVED' "
			+ "    AND APPL_STAT_CDE <> 'RETURNED' "
			+ "    AND APPL_STAT_CDE <> 'REJECTED' "
			+ "    AND APPL_STAT_CDE <> 'PENDING_APPL_ACCT' "
			+ "    AND APPL_STAT_CDE <> 'PENDING' "
			+ ") "
			+ "" , nativeQuery = true)
	List<ElApplHdrDAO> getApprovedApplsByUserId(@Param("user_id") String userId);

	@Query(value=""
			+ "SELECT ah.id as appl_hdr_id,  "
			+ "			                            ah.appl_nbr,  "
			+ "									    ah.appl_user_emplid as appl_user_emplid,  "
			+ "			                            nvl((SELECT tos FROM (SELECT * FROM el_inpost_staff_imp_v WHERE emplid = ah.appl_user_emplid ORDER BY primary_job_ind DESC) WHERE ROWNUM = 1), ' ') tos,  "
			+ "									    aps.sal_elemnt,  "
			+ "			                            ah.appl_user_name,  "
			+ "									    to_char(aps.pymt_start_dt, 'DD/MM/YYYY') as pymt_start_dt,  "
			+ "									    to_char(aps.pymt_end_dt, 'DD/MM/YYYY') as pymt_end_dt,  "
			+ "									    to_char(aps.pymt_rev_start_dt, 'DD/MM/YYYY') as pymt_rev_start_dt,  "
			+ "									    to_char(aps.pymt_rev_end_dt, 'DD/MM/YYYY') as pymt_rev_end_dt,  "
			+ "									    aps.empl_nbr as emp_rec_nbr,  "
			+ "									    apm.pymt_type_cde,  "
			+ "									    aet.pmt_currency,  "
			+ "									    aps.pymt_line_amt,  "
			+ "									    to_char(ah.appl_start_dt, 'DD/MM/YYYY') as appl_start_dt,  "
			+ "									    to_char(ah.appl_end_dt, 'DD/MM/YYYY') as appl_end_dt,  "
			+ "									    aps.br_no as br_no,  "
			+ "										aps.br_line_no,  "
			+ "										aps.br_dist_line_no,  "
			+ "						             (SELECT CASE WHEN EXISTS ( SELECT * FROM el_appl_pymt_method apm WHERE apm.appl_hdr_id = aps.appl_hdr_id AND apm.appl_hdr_id = ah.id  "
			+ "						                                        AND apm.pymt_category = 'MPF'  "
			+ "						                                        AND apm.pymt_amt > 0  "
			+ "						             					     ) THEN 'Y' ELSE 'N' END  FROM DUAL) hv_mpf,  "
			+ "						             (NVL(mpf2, 0)) mpf_amt,  "
			+ "                                     (NVL(mpf_br_no, ' ')) mpf_br_no,  "
			+ "                                     (NVL(mpf_br_line_no, 0)) mpf_br_line_no,  "
			+ "                                     (NVL(mpf_br_dist_line_no, 0)) mpf_br_dist_line_no,  "
			+ "			                         (SELECT max(aprv_dttm) FROM el_appl_aprv_status aas WHERE ah.id = aas.appl_hdr_id and aprv_type_cde IN ('FO_SR', 'FO_SFM') GROUP BY aas.appl_hdr_id) last_approval_time  "
			+ "									FROM el_appl_pymt_schedule aps  "
			+ "									LEFT JOIN  "
			+ "									    el_appl_pymt_method apm  "
			+ "									    ON aps.appl_pymt_method_id = apm.id  "
			+ "									LEFT JOIN  "
			+ "									    el_appl_el_type aet  "
			+ "									    ON aet.id = apm.appl_el_type_id   "
			+ "									LEFT JOIN  "
			+ "									    el_appl_hdr ah  "
			+ "									    ON ah.id = aps.appl_hdr_id  "
			+ "						LEFT JOIN  "
			+ "						(SELECT appl_hdr_id hdid, appl_pymt_method_id, pymt_line_amt mpf2, br_no mpf_br_no, br_line_no mpf_br_line_no, br_dist_line_no mpf_br_dist_line_no, pymt_start_dt FROM el_appl_pymt_schedule) mpf_aps "
			+ "						    ON mpf_aps.hdid = ah.id and trunc(aps.pymt_start_dt, 'mm') <= trunc(mpf_aps.pymt_start_dt, 'mm') and trunc(mpf_aps.pymt_start_dt, 'mm') <= trunc(aps.pymt_end_dt, 'mm') "
			+ "						        AND aps.proj_id = mpf_aps.proj_id AND aps.dept_id = mpf_aps.dept_id AND aps.fund_cde = mpf_aps.fund_cde AND aps.class_cde = mpf_aps.class_cde "
			+ "						        AND (SELECT pymt_category FROM el_appl_pymt_method "
			+ "						    WHERE id = mpf_aps.appl_pymt_method_id) = 'MPF' "
			+ "									WHERE aps.pymt_status_cde = 'SUBMIT'  "
			+ "			                            AND ah.appl_stat_cde = 'PENDING_FOPNB'  "
			+ "									    AND apm.pymt_category = 'SALARY'  "
			+ "										AND aps.pymt_submit_dttm <> to_date('17/11/1858', 'DD/MM/YYYY')"
			+ "ORDER BY pymt_start_dt, mpf_aps.pymt_start_dt, PYMT_SCHED_NO, PYMT_SCHED_LINE " , nativeQuery = true)
	List<Map<String, Object>> findPendingForPNB();

	@Query(value=""
			+ "SELECT ah.id as appl_hdr_id,  "
			+ "			                            aps.id appl_schedule_id, "
			+ "			                            ah.appl_nbr,  "
			+ "									    ah.appl_user_emplid as appl_user_emplid,  "
			+ "			                            nvl((SELECT tos FROM (SELECT * FROM el_inpost_staff_imp_v WHERE emplid = ah.appl_user_emplid ORDER BY primary_job_ind DESC) WHERE ROWNUM = 1), ' ') tos,  "
			+ "									    aps.sal_elemnt,  "
			+ "			                            ah.appl_user_name,  "
			+ "									    to_char(aps.pymt_start_dt, 'DD/MM/YYYY') as pymt_start_dt,  "
			+ "									    to_char(aps.pymt_end_dt, 'DD/MM/YYYY') as pymt_end_dt,  "
			+ "									    to_char(aps.pymt_rev_start_dt, 'DD/MM/YYYY') as pymt_rev_start_dt,  "
			+ "									    to_char(aps.pymt_rev_end_dt, 'DD/MM/YYYY') as pymt_rev_end_dt,  "
			+ "									    aps.empl_nbr as emp_rec_nbr,  "
			+ "									    apm.pymt_type_cde,  "
			+ "									    aet.pmt_currency,  "
			+ "									    aps.pymt_line_amt,  "
			+ "									    to_char(ah.appl_start_dt, 'DD/MM/YYYY') as appl_start_dt,  "
			+ "									    to_char(ah.appl_end_dt, 'DD/MM/YYYY') as appl_end_dt,  "
			+ "									    aps.br_no as br_no,  "
			+ "										aps.br_line_no,  "
			+ "										aps.br_dist_line_no,  "
			+ "										ah.mod_ctrl_txt, "
			+ "						             (SELECT CASE WHEN EXISTS ( SELECT * FROM el_appl_pymt_method apm WHERE apm.appl_hdr_id = aps.appl_hdr_id AND apm.appl_hdr_id = ah.id  "
			+ "						                                        AND apm.pymt_category = 'MPF'  "
			+ "						                                        AND apm.pymt_amt > 0  "
			+ "						             					     ) THEN 'Y' ELSE 'N' END  FROM DUAL) hv_mpf,  "
			+ "						             (NVL(mpf2, 0)) mpf_amt,  "
			+ "						             mpf_aps.pymt_start_dt mpf_mth,  "
			+ "                                     (NVL(mpf_br_no, ' ')) mpf_br_no,  "
			+ "                                     (NVL(mpf_br_line_no, 0)) mpf_br_line_no,  "
			+ "                                     (NVL(mpf_br_dist_line_no, 0)) mpf_br_dist_line_no,  "
			+ "			                         (SELECT max(aprv_dttm) FROM el_appl_aprv_status aas WHERE ah.id = aas.appl_hdr_id and aprv_type_cde IN ('FO_SR', 'FO_SFM') GROUP BY aas.appl_hdr_id) last_approval_time  "
			+ "									FROM el_appl_pymt_schedule aps  "
			+ "									LEFT JOIN  "
			+ "									    el_appl_pymt_method apm  "
			+ "									    ON aps.appl_pymt_method_id = apm.id  "
			+ "									LEFT JOIN  "
			+ "									    el_appl_el_type aet  "
			+ "									    ON aet.id = apm.appl_el_type_id   "
			+ "									LEFT JOIN  "
			+ "									    el_appl_hdr ah  "
			+ "									    ON ah.id = aps.appl_hdr_id  "
			+ "						LEFT JOIN  "
			+ "						(SELECT appl_hdr_id hdid, appl_pymt_method_id, pymt_line_amt mpf2, br_no mpf_br_no, br_line_no mpf_br_line_no, br_dist_line_no mpf_br_dist_line_no, trunc(pymt_start_dt, 'mm') start_dt, pymt_start_dt, proj_id, dept_id, fund_cde, class_cde  FROM el_appl_pymt_schedule) mpf_aps "
			+ "						    ON mpf_aps.hdid = ah.id and trunc(aps.pymt_start_dt, 'mm') <= start_dt and start_dt <= trunc(aps.pymt_end_dt, 'mm') "
			+ "						        AND aps.proj_id = mpf_aps.proj_id AND aps.dept_id = mpf_aps.dept_id AND aps.fund_cde = mpf_aps.fund_cde AND aps.class_cde = mpf_aps.class_cde "
			+ "						        AND (SELECT pymt_category FROM el_appl_pymt_method "
			+ "						    WHERE id = mpf_aps.appl_pymt_method_id) = 'MPF' "
			+ "									WHERE aps.pymt_status_cde = 'SUBMIT'  "
			+ "			                            AND ah.appl_stat_cde = 'PENDING_FOPNB'  "
			+ "									    AND apm.pymt_category = 'SALARY'  "
			+ "										AND aps.pymt_submit_dttm <> to_date('17/11/1858', 'DD/MM/YYYY') "
			+ " 									AND aps.br_no <> ' ' "
			+ " AND nvl((SELECT tos FROM (SELECT * FROM el_inpost_staff_imp_v WHERE emplid = ah.appl_user_emplid ORDER BY primary_job_ind DESC) WHERE ROWNUM = 1), ' ') LIKE :tos "
//			+ " AND upper(ah.appl_user_emplid) LIKE '%' || upper(:appl_user_emplid) || '%' "
			+ " AND upper(appl_user_name) LIKE '%' || upper(:appl_user_name) || '%' AND upper(sal_elemnt) LIKE '%' || upper(:sal_elemnt) || '%' "
			+ " AND TRUNC(CASE WHEN aps.pymt_rev_start_dt <> to_date('17111858','ddmmyyyy') THEN aps.pymt_rev_start_dt ELSE aps.pymt_start_dt END) >= TRUNC(:pymt_start_dt) "
			+ " AND TRUNC(CASE WHEN aps.pymt_rev_end_dt <> to_date('17111858','ddmmyyyy') THEN aps.pymt_rev_end_dt ELSE aps.pymt_end_dt END) <= TRUNC(:pymt_end_dt) "
//			+ " AND (:pymt_line_amt = -1 OR pymt_line_amt LIKE :pymt_line_amt) "
			+ " AND pymt_type_cde LIKE :pymt_type_cde "
			+ " ORDER BY ah.appl_nbr DESC, (CASE WHEN aps.pymt_rev_start_dt <> to_date('18581117', 'yyyymmdd') THEN aps.pymt_rev_start_dt ELSE aps.pymt_start_dt END), PYMT_SCHED_NO, PYMT_SCHED_LINE, mpf_aps.start_dt " , nativeQuery = true)
	List<Map<String, Object>> searchPendingForPNB(@Param("tos") String tos, 
//			@Param("appl_user_emplid") String appl_user_emplid, 
			@Param("appl_user_name") String appl_user_name, @Param("sal_elemnt") String sal_elemnt, 
			@Param("pymt_start_dt") Timestamp pymt_start_dt, @Param("pymt_end_dt") Timestamp pymt_end_dt, 
//			@Param("pymt_line_amt") BigDecimal pymt_line_amt, 
			@Param("pymt_type_cde") String pymt_type_cde );
	
	// Add here because not feasible to create a separate DAO for EL_BR_AMT_V, 3 columns not distinct
	@Query(value = "SELECT * FROM EL_BR_AMT_V WHERE br_no = :br_no ", nativeQuery = true)
	List<Map<String, Object>> findPymtRecordByBrNo(@Param("br_no") String brNo);
	
	@Query(value = "SELECT * FROM EL_BR_AMT_V ", nativeQuery = true)
	List<Map<String, Object>> findAllPymtRecord();
	
//	@Query(value=""
//			+ "SELECT ah.id as appl_hdr_id, "
//			+ "                            ah.appl_nbr, "
//			+ "						    ah.appl_user_emplid as appl_user_emplid, "
//			+ "                            nvl((SELECT tos FROM (SELECT * FROM el_inpost_staff_imp_v WHERE emplid = ah.appl_user_emplid ORDER BY primary_job_ind DESC) WHERE ROWNUM = 1), ' ') tos, "
//			+ "						    aps.sal_elemnt, "
//			+ "                            ah.appl_user_name, "
//			+ "						    to_char(aps.pymt_start_dt, 'DD/MM/YYYY') as pymt_start_dt, "
//			+ "						    to_char(aps.pymt_end_dt, 'DD/MM/YYYY') as pymt_end_dt, "
//			+ "						    to_char(aps.pymt_rev_start_dt, 'DD/MM/YYYY') as pymt_rev_start_dt, "
//			+ "						    to_char(aps.pymt_rev_end_dt, 'DD/MM/YYYY') as pymt_rev_end_dt, "
//			+ "						    aps.empl_nbr as emp_rec_nbr, "
//			+ "						    apm.pymt_type_cde, "
//			+ "						    aet.pmt_currency, "
//			+ "						    aps.pymt_line_amt, "
//			+ "						    to_char(ah.appl_start_dt, 'DD/MM/YYYY') as appl_start_dt, "
//			+ "						    to_char(ah.appl_end_dt, 'DD/MM/YYYY') as appl_end_dt, "
//			+ "						    aps.br_no as br_no, "
//			+ "							aps.br_line_no, "
//			+ "							aps.br_dist_line_no, "
//			+ "			             (SELECT CASE WHEN EXISTS ( SELECT * FROM el_appl_pymt_method apm WHERE apm.appl_hdr_id = aps.appl_hdr_id AND apm.appl_hdr_id = ah.id "
//			+ "			                                        AND apm.pymt_category = 'MPF' "
//			+ "			                                        AND apm.pymt_amt > 0 "
//			+ "			             					     ) THEN 'Y' ELSE 'N' END  FROM DUAL) hv_mpf, "
//			+ "			             (NVL((SELECT mpf_aps.pymt_line_amt FROM el_appl_pymt_schedule mpf_aps "
//			+ "			              INNER JOIN el_appl_pymt_method mpf_apm ON mpf_aps.appl_pymt_method_id = mpf_apm.id AND mpf_apm.pymt_category = 'MPF' "
//			+ "			              WHERE aps.appl_hdr_id = mpf_aps.appl_hdr_id AND aps.appl_hdr_id = ah.id AND trunc(aps.pymt_start_dt, 'mm') = trunc(mpf_aps.pymt_start_dt, 'mm')), 0)) mpf_amt, "
//			+ "                         (SELECT max(aprv_dttm) FROM el_appl_aprv_status aas WHERE ah.id = aas.appl_hdr_id and aprv_type_cde IN ('FO_SR', 'FO_SFM') GROUP BY aas.appl_hdr_id) last_approval_time "
//			+ "						FROM el_appl_pymt_schedule aps "
//			+ "						LEFT JOIN "
//			+ "						    el_appl_pymt_method apm "
//			+ "						    ON aps.appl_pymt_method_id = apm.id "
//			+ "						LEFT JOIN "
//			+ "						    el_appl_el_type aet "
//			+ "						    ON aet.id = apm.appl_el_type_id  "
//			+ "						LEFT JOIN "
//			+ "						    el_appl_hdr ah "
//			+ "						    ON ah.id = aps.appl_hdr_id "
//			+ "						WHERE aps.pymt_status_cde = 'SUBMIT' "
//			+ "                            AND ah.appl_stat_cde = 'PENDING_FOPNB' "
//			+ "						    AND apm.pymt_category = 'SALARY' "
//			+ "							AND aps.pymt_submit_dttm <> to_date('17/11/1858', 'DD/MM/YYYY') "
//			+ "ORDER BY pymt_start_dt " , nativeQuery = true)
//	List<Map<String, Object>> findPendingForPNB();
}
